CREATE TABLE book (
 id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
 title VARCHAR(100) NOT NULL,
 author VARCHAR(100),
 is_read BOOLEAN DEFAULT FALSE
);

CREATE TABLE game (
 id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
 title VARCHAR(100) NOT NULL,
 platform VARCHAR(100),
 is_played BOOLEAN DEFAULT FALSE
);

INSERT INTO book (title, author, is_read) VALUES 
('The Left Hand of Darkness', 'Ursula K. Le Guin', TRUE),
('Neuromancer', 'William Gibson', TRUE),
('A Brief History of Time', 'Stephen Hawking', FALSE);

INSERT INTO game (title, platform, is_played) VALUES 
('The Legend of Zelda: Skyward Sword', 'Nintendo Wii', TRUE)